---
title: "Clinicopathologic and outcome features"
---

```{r global, message = FALSE, warning = FALSE, echo = FALSE}
source("global.R")
attach(DF)
```

# **Clinical features**
## Age, in years
```{r age}
x <- age
tbl_nice(x)
g_nice(x)
```

***

## Sex
```{r sex}
x <- sex
tbl_nice(x)
g_nice(x)
```

***

# **Pathologic features**
## Tumor location
```{r location}
x <- location
tbl_nice(x)
g_nice(x)
```

***

## pT stage
```{r pt}
x <- pt
tbl_nice(x)
g_nice(x)
```

***

## High pT stage (> pT2)
```{r high_pt}
x <- high_pt
tbl_nice(x)
g_nice(x)
```

***

## Histologic grade
```{r grade}
x <- grade
tbl_nice(x)
g_nice(x)
```

***

## WHO histologic grade
```{r high_grade}
x <- high_grade
tbl_nice(x)
g_nice(x)
```

***

## Lymph nodes metastasis
```{r lymph_nodes}
x <- lymph_nodes
tbl_nice(x)
g_nice(x)
```

***

## Lymphovascular invasion
```{r lvi}
x <- lvi
tbl_nice(x)
g_nice(x)
```

***

# **Outcome**
## Follow-up, in months
```{r fu_progression}
x <- fu_progression
tbl_nice(x)
g_nice(x, bin = 12)
```

***

## Tumor recurrence
```{r recurrence}
x <- recurrence
tbl_nice(x)
g_nice(x)
```

***

## Tumor progression
```{r progression}
x <- progression
tbl_nice(x)
g_nice(x)
```

***

## Final outcome
```{r outcome}
x <- outcome
tbl_nice(x)
g_nice(x)
```

***

## Overall mortality
```{r dead}
x <- dead
tbl_nice(x)
g_nice(x)
```

***

## Cancer-related mortality
```{r dod}
x <- dod
tbl_nice(x)
g_nice(x)
```

***
